### ISSUE TITLE
Wrong character.b3d uv-mapping

### ISSUE THREAD

**Issue by xunto** [minetest/minetest_game#1145]
Arms' and legs' textures are inverted.

**Now:** [link](http://storage7.static.itmages.ru/i/16/0618/h_1466275477_5205527_936c47609e.png)
**Should:** [link](http://storage7.static.itmages.ru/i/16/0618/h_1466275477_5051309_080837be55.png)

**Skin:** [link](https://itmages.ru/image/view/4441170/6075e5fa)

It ruins the whole idea of having skin format that is similar to minecraft's.

**Comment by hunterdelyx1** [comment]
Oh, forgot.

[skin](https://itmages.ru/image/view/4441170/6075e5fa)

**Comment by Wuzzy2** [comment]
Itsn't this an issue with Minetest instead of Minetest Game?

**Comment by hunterdelyx1** [comment]
It's minetest-game issue because uv-mapping is set for model. Models are stored in minetest-game repo([link](https://github.com/minetest/minetest_game/tree/master/mods/default/models)). How can it be related to engine?

**Comment by paramat** [comment]
Where did the yellow and green areas on arms and legs in the skin go?

**Comment by paramat** [comment]
Sorry to highlight you but, @sofar

**Comment by stujones11** [comment]
This is not a new issue, in fact it was fixed once before #112 though I guess it would need to be re-done for b3d format anyway.

**Comment by sofar** [comment]
Ah, yes, this should totally be fixed.

**Comment by hunterdelyx1** [comment]
@stujones11 I've tested this PR and it's incomplete. Only front and back of legs are fixed, hands and inside edges of legs are still broken.

**Comment by paramat** [comment]
#1147 is merged.
