### ISSUE TITLE
Actually rename Minetest (the subgame)

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest_game#480]
This issue is a follow-up of #437.

Long story short, it has been decided to rename this subgame to “Minetest Game”.

Now since we got that done, the subgame has not been actually renamed yet.

A couple of files in the subgame must be changed. The relevant files should use the new name “Minetest Game” constantly. Mentions of “minetest_game” or even “Minetest” (in the sense of “subgame”) should be removed or replaced by “Minetest Game”. I suggest that from now on, “minetest_game” should only be used to refer to this repository. It should be (lightly) discouraged to use this term to refer to this subgame. The term “Minetest” alone should *not* be used anymore to refer to this subgame.

The following files need to be updated:

* `menu/header.png` (new or altered image must be drawn)
* `game.conf`
* `README.txt`
* `game_api.txt`
* `minetest.conf.example`
* (mention any files I forgot)

Additionally, the desciption of this repository on GitHub should be changed as well.

TODO list for your convenience:
* [x] Change `menu/header.png`
* [x] Change `game.conf`
* [x] Change `README.txt`
* [x] Change`game_api.txt`
* [x] Change `minetest.conf.example`
* [x] Check out other readme files of mods and change them if needed
* [x] Make sure the name “Minetest Game” is used consistently throughout this subgame
* [x] Change repo description on GitHub

Edit: After all or most of this has been done, also post a thread into the News forum:
https://forum.minetest.net/viewforum.php?f=18

* [x] Post a thread into the news forum

Edit 2: And the wikis, too.
* [x] Update the developer wiki
* [x] Update the community wiki

**Comment by kilbith** [comment]
Cool, this will greatly improves the game ...

**Comment by PilzAdam** [comment]
@kilbith what? How does a name improve a game?

@Wuzzy2 what needs to be changed in the repo description?

**Comment by Wuzzy2** [comment]
@PilzAdam:

Current description: “The main game for the Minetest game engine [minetest_game] [https://github.com/minetest/minetest/]”

I suggest something like: “Minetest Game: The main subgame for Minetest [https://github.com/minetest/minetest/].”

**Comment by kilbith** [comment]
@PilzAdam Sarcasm...

**Comment by est31** [comment]
I think directory names shouldn't contain spaces.

**Comment by PilzAdam** [comment]
Also update the dev and user wiki.

**Comment by Wuzzy2** [comment]
@est31: Nobody was talking about directory names. I am only talking about the “human-readable” name (the actual name in the interface and for communication, not about any names which may be used internally).

**Comment by Wuzzy2** [comment]
I have created 2 simple logos, feel free to use them:

https://forum.minetest.net/viewtopic.php?f=3&t=10426&start=25#p176675

---
@PilzAdam @ShadowNinja

**Comment by PilzAdam** [comment]
@Wuzzy2 I'd prefer the new header being based on the first header from #341 instead of the current one.

**Comment by Wuzzy2** [comment]
What about these?:
https://i.imgur.com/BO1fV1i.png
https://i.imgur.com/fbcQHjh.png
https://i.imgur.com/bGWNRMp.png

**Comment by PilzAdam** [comment]
Why yellow?

**Comment by C1ffisme** [comment]
I think it's meant to look more like a Minecraft Splash.

**Comment by Wuzzy2** [comment]
Because this was the first color which came in my mind. There is not really a logic behind this.

**Comment by kilbith** [comment]
Yellow offers a sweet contrast and is not "flashy". I give my weightless vote for the 1st header (inclinated Game)

**Comment by sfan5** [comment]
> What about these?:
https://i.imgur.com/BO1fV1i.png
https://i.imgur.com/fbcQHjh.png
https://i.imgur.com/bGWNRMp.png

IMO the yellow text in each one of these looks horrible.

**Comment by C1ffisme** [comment]
@sfan5 Um, which color would you rather have?

It gives it a sort of Minecrafty feeling, like the game is similar to minecraft. Of course, perhaps we aren't entirely minecraft. We could use a few mobs here and blocks there, but still, we want minecraft to minetesters to get a sort-of familliar feeling.

**Comment by Wuzzy2** [comment]
I am not the best artist, sorry. :-(
But anyone is invited to try to make a better logo. xD

**Comment by kilbith** [comment]
@PilzAdam @sfan5 

It's okay if I take https://github.com/minetest/minetest_game/pull/489 in charge with your suggestions since BlockMen is long-time MIA (again) ?

**Comment by nanepiwo** [comment]
I, personally, do not like the yellow text because it separates the two words too much. IIRC in Minecraft the yellow text is the version number, and it shouldn't flow too well with the game name. Here, I think the word "Game" should be a similar font as the word "Minetest."

**Comment by CraigyDavi** [comment]
Leave header.png, we don't need to put "Game" on it. Just as long as the header doesn't say "minetest_game".

**Comment by Wuzzy2** [comment]
Why? The subgame has been renamed to “Minetest Game”, so leaving the header as “Minetest” would be confusing.

**Comment by Wuzzy2** [comment]
So it seems the subgame has not been renamed at all for Minetest 0.4.13, contrary to prior agreements.

The main menu and game.cfg *still* calls it just “Minetest”, the big text logo *still* just says “Minetest” etc. *Nothing* on this todo list has been done.

Frankly, I feel a bit pissed off now. :-(

**Comment by Ferk** [comment]
Renaming "Minetest", the game, into "Minetest Game" is not much of a change of name anyway.

People is gonna continue colloquially using the same name for the engine and the game. Maybe it would make more sense to rename the engine... "MineGen" or something.

**Comment by paramat** [comment]
> I'd prefer the new header being based on the first header from #341

Me too. I don't like the submitted header images here or in #489. Simply 'MINETEST GAME' in one of the first 2 styles in #341 would be my preference.

**Comment by paramat** [comment]
This needs doing, i suggest separating the new header image into a separate PR to be merged later.
The first commit of #489 contains the other necessary text changes, i will probably submit a PR for those myself. I might even attempt a new header image.

**Comment by paramat** [comment]
I merged a commit similar to #489.
8e51f318b3ac9130bb1be4644b379f64e8f60b02

**Comment by Wuzzy2** [comment]
This issue is not fully resolved, see the checklist in the first post.
Most imporantly, the menu header is still untouched.

**Comment by PilzAdam** [comment]
I don't see what needs to be changed in the current repo description; it doesn't collide with th new terminology.

Reopening because header is still missing.

**Comment by paramat** [comment]
Sorry i should not have closed this.
I'm working on a new header image.

**Comment by paramat** [comment]
![minetest main menu _002](https://cloud.githubusercontent.com/assets/3686677/10260927/58fa57c2-6979-11e5-900f-2848e2ec8905.png)

This is with default GUI scaling and a 600x160 header image, roughly equal to the height of the current one.
Words can be made inline if you prefer, size can be changed.
Each letter is 16x16 pixles, using the stone texture with stone brick shading.
If it overlaps the GUI tabs it's darkness works well with the tabs' transparency.

**Comment by ShadowNinja** [comment]
@paramat: There's a seperate copy at `textures/base/pack/menu_header.png` for the non-game screens.

**Comment by kilbith** [comment]
@paramat  The style looks good and consistent. But some remarks : 
- The letters should be slightly spaced at each other for readability.
- `MINETEST` should be centered, and `GAME` showed smaller somewhere over or below `MINETEST`, perhaps as a "flag" on the right (evoking an auxiliary project rather than something monolitic).

This is not essential to hoist `GAME` as such. The user don't cares, it's the default game and the singularity of the name `Minetest` should remain central and self-explanatory.

**Comment by Wuzzy2** [comment]
Paramat, I like your work. I am just confused why you use sizes like 768 and 960. Why not using 1 actual pixel per “pixel” because Minetest scales it anyways? As far I know, Minetest won't apply any smoothing after scaling, so the pixel style is retained even if up-scaled.
I agree with kilbith in that there should be a minimal spacing between letters. Probably just 1 “pixel” may suffice.
But your text logo also seems to appear a bit small on the main menu. Did you leave some empty space above the text logo or is it just the way how it ended up in this screen? (not really important btw)

Kilbith, I am not sure if your 2nd suggestion is a good idea. The text logo may turn out to be scaled too small if “GAME” is moved below “MINETEST”.

**Comment by paramat** [comment]
Thanks for the feedback.

I prefer the letters touching, they are meant to be a line of nodes and one vertical slab, that have been carved into letters, the contact suggests a 'construction' to imply the construction aspect of the game, it looks chunkier, heavier and more solid this way. I think i will increase the contrast of the bevel shading, this will improve readability.

Having 'game' as a small label added to a large Minetest was used in the other 2 submissions and i find that cheap and cheesy looking. The name is 'Minetest Game', the second word is equal in importance to the first.

I didn't know the image is scaled, is this always done or only on small screens? Maybe this is why it doesn't seem to get bigger when i use 960px instead of 768px? Anyway yes it's maybe a little too small, maybe the 960px version is being downscaled.

The original image is made at pixel resolution (16x16px for each letter) and is 192x16px, i then scaled it up by x4 or x5 (with no interpolation of course) to get 768 and 960px. I'll try the 192x16px image to see how that behaves when scaled.

There is no empty space around the image.

**Comment by paramat** [comment]
![minetest main menu _006](https://cloud.githubusercontent.com/assets/3686677/10265704/da50a2d0-6a33-11e5-892a-d168c229c3ec.png)

This is with default GUI scaling. Header image is 192x16px and is upscaled automatically to what you see here. Before i tried making the words larger but Minetest must have been scaling the image back down.

Being used to the current header these words may seem a little small at first, but i find they look better this size, cooler and understated. The spacing makes the menu screen seem less cluttered. It also creates more space for changing the GUI scale or using a larger menu in future.

**Comment by kilbith** [comment]
+1 from me (except the prominence of `GAME`). The carved `I` is an improvement.

**Comment by PilzAdam** [comment]
I like the shape of the letters, but I think the grey on blue background looks bad.

**Comment by Wuzzy2** [comment]
I think this header is good now. I don't care so much about spacing, so I give my

[Wuzzy Seal of Approval].

:D

**Comment by paramat** [comment]
@PilzAdam the current header uses a light grey stone texture, perhaps i should use a lighter grey version of the stone texture for this? It does look quite dark here.

**Comment by PilzAdam** [comment]
@paramat the current texture isn't good either.

**Comment by CraigyDavi** [comment]
@BlockMen Do you have the source to the original header image? I think it's a lot easier to just use exactly the same style text as it is currently.

**Comment by paramat** [comment]
I'll open a PR for this as it is, to get more dev attention and feedback. I think it's okay as it is, or it perhaps could have a lighter stone texture to appear brighter against the sky.

**Comment by paramat** [comment]
New header merged.

**Comment by Wuzzy2** [comment]
Today I have checked whether “Minetest Game” is used consistently in the subgame (especially in all those text files). This is *almost* true.

Only line 166 in `game_api.txt` uses “minetest_game” inappropriately. Change this line and I can tick off another item from the TODO list.

**Comment by PilzAdam** [comment]
c15bd9d529812a14d516f8063baea903133cadbe

**Comment by Wuzzy2** [comment]
Thanks. I have updated the wikis, now only 2 items are left on the TODO list.
Feel free to skip those items if you don't feel like it and close the issue right now.

But if you skip the news post, please at least mention the new name in the next Minetest release or at some earlier point of time.

**Comment by paramat** [comment]
Repo description has been updated thanks to celeron55.
I'll make a news post in forum now.

**Comment by paramat** [comment]
https://forum.minetest.net/viewtopic.php?f=18&t=14081
