### ISSUE TITLE
Glass panes (iron bars) between sofar's walls

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest_game#920]
Issues for now:
* glass pane and iron bar look like this between two walls: https://i.imgur.com/qKaMCfy.png
* two glass panes or iron bars between two walls: https://i.imgur.com/7B4JPJp.png

**Comment by everamzah** [comment]
xpanes needs to be updated to use ndt_connected, i think, and then it will connect alrighty.

**Comment by paramat** [comment]
First we need sandstone cobble.

**Comment by sofar** [comment]
The image https://i.imgur.com/qKaMCfy.png was a bug - walls were never meant to connect to fences. This was fixed in core, and won't happen anymore.

**Comment by sofar** [comment]
The walls are all made out of "Cobblestone". If there's another, lighter version of cobblestone around, then we can add cobblestone walls for that, but that's not the case right now.

**Comment by sofar** [comment]
I feel this can be closed. This contains only 1 bug (which was fixed here: https://github.com/minetest/minetest/commit/5a40a7dad8cbf46320c3b5dd1122808eb4919b62 )

The second part is a feature request that is debatable, and not a bug. Bugs and Features should not be combined into one issue. Even bugs should not be combined.

**Comment by Fixer-007** [comment]
>I feel this can be closed. This contains only 1 bug (which was fixed here: minetest/minetest@5a40a7d )
No, it does not fix first issue for me :( I still see crossed xpane or iron bars between two walls

Also, what about this bug?
* two glass panes or iron bars between two walls: https://i.imgur.com/7B4JPJp.png

**Comment by everamzah** [comment]
Why doesn't XPanes use NDT_CONNECTED?

**Comment by Ekdohibs** [comment]
@everamzah I had exactly the same question.

**Comment by sofar** [comment]
I'm dumb.I even said in IRC this was valid.

Walls currently connect to ```group:cracky``` which should probably just be removed, as ```group:stone``` is probably enough already.

**Comment by sofar** [comment]
Fixed by #935.

There were quite a few other nodes in group:cracky, so I took it out.

**Comment by paramat** [comment]
935 merged.
